### ISSUE TITLE
bugbot doesn't play nicely with the Slack IRC bridge

### ISSUE THREAD

**Issue by rvandermeulen** [emceeaich/bmo-bugbot#1]
4:23:57 PM - emceeaich: This is after a history of being corrected in LJ/DW comments over the years.
4:26:25 PM - emceeaich: Meanwhile, can I get interested parties feedback on a bug?
4:26:31 PM - SLACK: Here is the information on a bug which @emceeaich asked about:
4:26:31 PM - SLACK: NO FALLBACK DEFINED

**Comment by emceeaich** [comment]
Ah! https://api.slack.com/docs/message-attachments

use the 'fallback' field in the message attachments.
